# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PubConf
email: hello@pubconf.com
description: >
  Rapid-fire Ignite talks from inspirational developers in the relaxed
  atmosphere of The Pepys pub, PubConf will be a uniquely entertaining and 
  insightful event.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pubconf.io" # the base hostname & protocol for your site

googleplus_username: 100352791344568085197
facebook_username: pubconf
twitter_username: pubconf

# Build settings
markdown: kramdown
gems:
  - jekyll-assets

exclude:
  - "Gemfile*"
